# -*- coding: utf-8 -*-
"""Regresionlineal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UeVlVG7v6vl2GbsTEtWFRibB0S3hbmCj
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import r2_score

datos=pd.read_csv('movies.csv', sep=',')

df = pd.DataFrame(datos)

datos.describe()

x=df['movie_facebook_likes']
y=df['imdb_score']

X=x[:,np.newaxis]
print(X)

regr=linear_model.LinearRegression()
print(regr.fit(X[0:12],y[0:12])) #se envian los datos de prueba 80%
print(regr.coef_)
m=regr.coef_[0]
b=regr.intercept_
y_p=m*X+b
print('y={0}*x+{1}'.format(m,b))
print('El valor de r2 es: ' ,r2_score(y,y_p))

print(regr.predict(X)[12:15]) #Los valores predecidos por el modelo

print(y[12:15]) #Los valores dada la base de datos

import matplotlib.pyplot as plt

import matplotlib.pyplot as plt
plt.scatter(x,y,color='red')
plt.plot(x,y_p,color='blue')
plt.title('Regresion lineal', fontsize=16)
plt.xlabel('Likes Facebook', fontsize=13)
plt.ylabel('Calificacion IMDB', fontsize=13)